### ISSUE TITLE
Have you tried to support Bionic LibC? Developed by Google, should be compatible with GlibC and Musl, its great for systems with limited RAM and its very optimized...

### ISSUE THREAD

**Issue by xplshn** [CobaltBSD/cbtutils#1]
Also... https://github.com/openbsd/src/tree/master/lib/libc

Google's Bionic LibC itself is based out of OpenBSD's implementation.

For a truly POSIX, secure, implementation

**Comment by CobaltBSD** [comment]
Thanks, I'll check it out. Main thing we need is full compatibility with glibc, so that pre-compiled programs can run.

The main reason I chose glibc is because it leaks out a bunch of internal symbols into programs built with it that make it difficult to swap out without severely reducing compatibility or increasing overhead.

Edit: Bionic libc without heavy patching seems to depend on the entirety of Android and its build system, so supporting it probably isn't feasible in the short term.

**Comment by xplshn** [comment]
I see. But will you start using non-standard features?

Most programs compiled with GlibC can't run on system's based on standards compliant libs but it does work the other way around.

**Comment by CobaltBSD** [comment]
I don't intend to use non-standard features, but glibc leaks its internals out in the programs compiled using it, which results in the issue you described whether I use non-standard features or not. It is that or lack support for a large amount of software, drivers, etc.

Unfortunately either it's glibc, and all the associated problems, or lack support for virtually all pre-compiled software without extensive workarounds.

**Comment by xplshn** [comment]
Maybe with gcompat? I have Void and Gcompat installed, I can game on my distro just fine, and not using Wine! But yeah, things like AppImages often fail. I suggest you use Void's repo as an starting point, maybe even adopt their package manager, its Unix like, its blazing fast and it runs on various OSes like Alpine.

Remember, its your project, what matters is that you like what you do. Still, I'm thrilled you are working on this, can't wait for a release, I've been looking for an OS that has the things I love of BSD, and the compatibility Linux offers!
